<?php
$cds = $this->cds;
?>
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lista de CDs</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css">
    <link rel="stylesheet" href="/lifefile/public/css/cd_list.css">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
</head>

<body>

    <!-- Modal -->
    <div class="modal fade" id="createCdModal" tabindex="-1" aria-labelledby="createCdModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="createCdModalLabel">Título del Modal</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <label for="artista" class="form-label">Artista</label>
                    <input type="text" value="Diomedes diaz" class="form-control mb-3" id="artista" placeholder="Artista">
                    <label for="titulo" class="form-label">Título</label>
                    <input type="text" value="lluvia de verano" class="form-control mb-3" id="titulo" placeholder="Titulo">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                    <button type="button" id="submit" class="btn btn-primary">Guardar cambios</button>
                </div>
            </div>
        </div>
    </div>

    <nav class="navbar navbar-expand-lg navbar-dark mb-4">
        <div class="container">
            <a class="navbar-brand" href="../index/"><i class="fas fa-compact-disc me-2"></i>CDs Store</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item"><a class="nav-link" href="../index/">Inicio</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        <div class="row">
            <div class="col-12">
                <h1 class="text-center mb-4 mt-3">Lista de CDs</h1>
                <button data-bs-toggle="modal" data-bs-target="#createCdModal" class="btn btn-primary mb-3" " role=" button">
                    <i class="fas fa-plus me-2"></i> Add
                </button>

                <div class="table-responsive">
                    <table class="table table-striped table-hover">
                        <thead>
                            <tr>
                                <th>Artista</th>
                                <th>Titulo</th>
                                <th>Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($cds as $cd) : ?>
                                <tr>
                                    <td><?= $cd['artist'] ?></td>
                                    <td><?= $cd['title'] ?></td>
                                    <td>
                                        <a type="button" class="btn btn-primary" href="/cd/update/<?= $cd->id ?>" role="button">
                                            <i class="fas fa-edit me-2"></i> Edit
                                        </a>
                                        <a type="button" class="btn btn-danger" href="/cd/delete/<?= $cd->id ?>" role="button">
                                            <i class="fas fa-trash-alt me-2"></i> Delete
                                        </a>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <script>
        window.onload = () => {
            const titulo = document.getElementById('titulo');
            const artista = document.getElementById('artista');
            const submit = document.getElementById('submit');
            const showErrors = (msg) => {
                Swal.fire({
                    icon: 'error',
                    title: 'Error',
                    text: msg
                });
                return;
            };
            const validateArtist = () => {
                let isValid = true;

                // Reset error messages
                // Validate artista
                if (!artista.value.trim() || artista.value.length < 5) {
                    showErrors('Enter a valid artist');
                    isValid = false;
                }


                // Validate titulo
                if (!titulo.value.trim() || titulo.value.length < 3) {
                    showErrors('Enter a valid title');
                    isValid = false;
                }

                return isValid;
            }
            submit.addEventListener('click', async () => {
                if (validateArtist()) {
                    try {
                        const res = await fetch('create/', {
                            method: 'POST',
                            headers: {
                                'Content-Type': 'application/json',
                                'Accept': 'application/json'
                            },
                            body: JSON.stringify({
                                artist: artista.value.trim(),
                                title: titulo.value.trim()
                            })
                        });
                        const data = await res.json();
                        if (res.ok) {
                            Swal.fire({
                                icon: 'success',
                                title: 'Success',
                                text: data.success
                            })
                        }
                        if (res.status === 400) {
                            Swal.fire({
                                icon: 'error',
                                title: 'Error',
                                text: data.error
                            })
                        }
                    } catch (err) {
                        Swal.fire({
                            icon: 'error',
                            title: 'Error',
                            text: err.message
                        })
                    }
                }
            });

        }
    </script>
    <script src="sweetalert2.all.min.js"></script>

</body>

</html>